<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
  public function findAuthorByName($name)
  {

    $dql = 'SELECT a.id FROM AppBundle:Author AS a WHERE a.name = :name';

    return $this->getEntityManager()
      ->createQuery($dql)
      ->setParameter('name', $name)
      ->getOneOrNullResult();
  }

  public function findAuthorById($id)
   {
       $dql = 'SELECT a FROM AppBundle:Author AS a WHERE a.id = :id';

       return $this->getEntityManager()
           ->createQuery($dql)
           ->setParameter('id', $id)
           ->getOneOrNullResult();
   }
}
