<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Form\Model\SearchBookParameter;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
  public function findBookById($id)
   {
       $dql = 'SELECT b FROM AppBundle:Book AS b WHERE b.id = :id';

       return $this->getEntityManager()
           ->createQuery($dql)
           ->setParameter('id', $id)
           ->getOneOrNullResult();
   }

   public function findByParameters(SearchBookParameter $searchParameters)
   {
     $dql = 'SELECT b FROM AppBundle:Book AS b';
     $where = [];
     $parameters = [];

     if (!empty($searchParameters->priceFrom)) {
       $where[] = 'b.price >= :price_from';
       $parameters['price_from'] = $searchParameters->priceFrom;
     }
     if (!empty($searchParameters->priceTo)) {
       $where[] = 'b.price <= :price_to';
       $parameters['price_to'] = $searchParameters->priceTo;
     }
     if (!empty($searchParameters->author)) {
       $where[] = 'b.idAuthor = :author_id';
       $parameters['author_id'] = $searchParameters->author;
     }
     if ($where) {
       $dql .= " WHERE " . implode(' AND ', $where) . " ";
     }
     return $this->getEntityManager()
      ->createQuery($dql)
      ->setParameters($parameters)
      ->getResult();
   }
}
