<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends EntityRepository
{
  public function findPublisherByName($publisherName)
  {
    $dql = 'SELECT p FROM AppBundle:Publisher AS p WHERE p.publisherName = :publisherName';

    return $this->getEntityManager()
      ->createQuery($dql)
      ->setParameter('publisherName', $publisherName)
      ->getOneOrNullResult();
  }

  public function findPublisherById($id)
  {
     $dql = 'SELECT p FROM AppBundle:Publisher AS p WHERE p.id = :id';

     return $this->getEntityManager()
         ->createQuery($dql)
         ->setParameter('id', $id)
         ->getOneOrNullResult();
  }
}
