<?php

namespace AppBundle\Repository;

use AppBundle\Form\Model\User;
use Doctrine\ORM\EntityRepository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  public function findEmailUser($email)
  {
    $dql = 'SELECT FROM AppBundle:User user WHERE user.email = :email';

    return $this->getEntityManager()
      ->createQuery($dql)
      ->setParameter('email', $email)
      ->getOneOrNullResult();
    }

    public function findUserById($id)
     {
         $dql = 'SELECT u FROM AppBundle:User AS u WHERE u.id = :id';

         return $this->getEntityManager()
             ->createQuery($dql)
             ->setParameter('id', $id)
             ->getOneOrNullResult();
     }
}
